# Generated by Django 4.2.7 on 2025-05-22 17:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JournalCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("color", models.CharField(default="#4287f5", max_length=20)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Journal Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("very_negative", "Very Negative"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                            ("positive", "Positive"),
                            ("very_positive", "Very Positive"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_private", models.BooleanField(default=True)),
                ("shared_with_therapist", models.BooleanField(default=False)),
                (
                    "weather",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sunny", "Sunny"),
                            ("cloudy", "Cloudy"),
                            ("rainy", "Rainy"),
                            ("stormy", "Stormy"),
                            ("snowy", "Snowy"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "activities",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exercise", "Exercise"),
                            ("reading", "Reading"),
                            ("meditation", "Meditation"),
                            ("socializing", "Socializing"),
                            ("working", "Working"),
                            ("cooking", "Cooking"),
                            ("gardening", "Gardening"),
                            ("dancing", "Dancing"),
                            ("gaming", "Gaming"),
                            ("traveling", "Traveling"),
                            ("shopping", "Shopping"),
                            ("listening_to_music", "Listening to Music"),
                            ("watching_tv", "Watching TV"),
                            ("yoga", "Yoga"),
                            ("walking", "Walking"),
                            ("running", "Running"),
                            ("painting", "Painting"),
                            ("writing", "Writing"),
                            ("cleaning", "Cleaning"),
                            ("photography", "Photography"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="journal.journalcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Journal Entries",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
