# Generated by Django 4.2.14 on 2025-04-27 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        help_text="Hex color code (e.g. #FF0000)", max_length=7
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon identifier", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Journal Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="journalentry",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name_plural": "Journal Entries",
            },
        ),
        migrations.AddField(
            model_name="journalentry",
            name="activities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="is_private",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="location",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="mood",
            field=models.CharField(
                blank=True,
                choices=[
                    ("very_negative", "Very Negative"),
                    ("negative", "Negative"),
                    ("neutral", "Neutral"),
                    ("positive", "Positive"),
                    ("very_positive", "Very Positive"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="shared_with_therapist",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="weather",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["user", "-date"], name="journal_jou_user_id_aca642_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["mood"], name="journal_jou_mood_16bb2b_idx"),
        ),
        migrations.AddField(
            model_name="journalcategory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entries",
                to="journal.journalcategory",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="journalcategory",
            unique_together={("name", "user")},
        ),
    ]
