# Generated by Django 4.2.14 on 2025-04-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_journalcategory_alter_journalentry_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalentry",
            name="category",
        ),
        migrations.DeleteModel(
            name="JournalCategory",
        ),
    ]
