# Generated by Django 4.2.14 on 2025-04-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0003_remove_journalentry_category_delete_journalcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalentry",
            name="location",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="tags",
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="activities",
            field=models.CharField(
                blank=True,
                choices=[
                    ("exercise", "Exercise"),
                    ("reading", "Reading"),
                    ("meditation", "Meditation"),
                    ("socializing", "Socializing"),
                    ("working", "Working"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="weather",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sunny", "Sunny"),
                    ("cloudy", "Cloudy"),
                    ("rainy", "Rainy"),
                    ("stormy", "Stormy"),
                    ("snowy", "Snowy"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
