# Generated by Django 4.2.14 on 2025-04-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0004_remove_journalentry_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="activities",
            field=models.CharField(
                blank=True,
                choices=[
                    ("exercise", "Exercise"),
                    ("reading", "Reading"),
                    ("meditation", "Meditation"),
                    ("socializing", "Socializing"),
                    ("working", "Working"),
                    ("cooking", "Cooking"),
                    ("gardening", "Gardening"),
                    ("dancing", "Dancing"),
                    ("gaming", "Gaming"),
                    ("traveling", "Traveling"),
                    ("shopping", "Shopping"),
                    ("listening_to_music", "Listening to Music"),
                    ("watching_tv", "Watching TV"),
                    ("yoga", "Yoga"),
                    ("walking", "Walking"),
                    ("running", "Running"),
                    ("painting", "Painting"),
                    ("writing", "Writing"),
                    ("cleaning", "Cleaning"),
                    ("photography", "Photography"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
