# Generated by Django 4.2.14 on 2025-02-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='crisis_alert_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_mood_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='passcode_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='ai_personalization_level',
            field=models.IntegerField(default=2, help_text='0=Off, 1=Basic, 2=Advanced'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='crisis_alert_sensitivity',
            field=models.IntegerField(default=1, help_text='0=Low, 1=Medium, 2=High'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stress_level',
            field=models.IntegerField(default=0, help_text='Scale from 1-10'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='therapy_preferences',
            field=models.JSONField(blank=True, help_text='Preferred therapy exercises', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wearable_data',
            field=models.JSONField(blank=True, help_text='Fitbit/Apple Watch data', null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='crisis_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='journaling_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('voice', 'Voice'), ('both', 'Both')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='passcode_protection',
            field=models.BooleanField(default=False),
        ),
    ]
