# Generated by Django 4.2.14 on 2025-03-14 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='profile_type',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='profile_type',
        ),
    ]
