# Generated by Django 5.1.7 on 2025-03-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "notifications",
            "0004_rename_is_active_notificationtype_default_enabled_and_more",
        ),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreferences",
            name="notification_preferences",
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="disabled_notification_types",
            field=models.ManyToManyField(
                blank=True, to="notifications.notificationtype"
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="in_app_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
