# Generated by Django 4.2.7 on 2025-05-27 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpreferences",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="userpreferences",
            name="users_userp_user_id_355e4b_idx",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="dark_mode",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="disabled_notification_types",
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="notification_preferences",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="push_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="theme",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark")],
                default="light",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="timezone",
            field=models.CharField(default="UTC", max_length=50),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="in_app_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name="userpreferences",
            table="users_userpreferences",
        ),
    ]
