# Generated by Django 4.2.14 on 2025-03-11 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("patient", "Patient"), ("therapist", "Therapist")],
                default="patient",
                help_text="Designates whether this user is a patient or therapist",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="TherapistProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                (
                    "availability",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Therapist availability schedule",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Therapist profiles",
            },
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "stress_level",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "wearable_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional wearable device data",
                        null=True,
                    ),
                ),
                (
                    "therapy_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional therapy preferences",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Patient profiles",
            },
        ),
    ]
