# Generated by Django 4.2.14 on 2025-03-11 23:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_user_type_therapistprofile_patientprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
