# Generated by Django 5.1.7 on 2025-03-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userpreferences_notification_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Enable email notifications'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='in_app_notifications',
            field=models.BooleanField(default=True, help_text='Enable in-app notifications'),
        ),
    ]
