# Generated by Django 4.2.7 on 2025-05-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userpreferences_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpreferences",
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
            },
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="dark_mode",
            field=models.BooleanField(default=False),
        ),
    ]
