# Generated by Django 4.2.14 on 2025-03-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="dark_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="notification_preferences",
            field=models.JSONField(default=dict),
        ),
    ]
