# Generated by Django 4.2.7 on 2025-05-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_initial"),
        ("users", "0003_alter_userpreferences_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpreferences",
            options={"verbose_name_plural": "User preferences"},
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="notification_preferences",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="push_notifications",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="theme",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="timezone",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="disabled_notification_types",
            field=models.ManyToManyField(
                blank=True, to="notifications.notificationtype"
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="email_notifications",
            field=models.BooleanField(
                default=True, help_text="Enable email notifications"
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="in_app_notifications",
            field=models.BooleanField(
                default=True, help_text="Enable in-app notifications"
            ),
        ),
        migrations.AddIndex(
            model_name="userpreferences",
            index=models.Index(fields=["user"], name="users_userp_user_id_355e4b_idx"),
        ),
        migrations.AlterModelTable(
            name="userpreferences",
            table=None,
        ),
    ]
