# Generated by Django 4.2.14 on 2025-02-25 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_customuser_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreferences',
            options={'verbose_name_plural': 'User preferences'},
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='accessibility',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='ai_personalization_level',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='crisis_alert_sensitivity',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='accessibility_settings',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='theme',
            field=models.CharField(default='light', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='notification_settings',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
