# Generated by Django 4.2.7 on 2025-05-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_is_online"),
        ("users", "0004_customuser_is_online_customuser_last_seen"),
    ]

    operations = []
