# Generated by Django 4.2.14 on 2025-03-12 22:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userpreferences_dark_mode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Patient Profiles'},
        ),
        migrations.AlterModelOptions(
            name='therapistprofile',
            options={'verbose_name_plural': 'Therapist Profiles'},
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='stress_level',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='therapy_preferences',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='wearable_data',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='availability',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='current_medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='last_appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='next_appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='pain_level',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='treatment_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='available_days',
            field=models.JSONField(blank=True, default=dict, help_text='Weekly availability schedule', null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='languages_spoken',
            field=models.JSONField(blank=True, default=list, help_text='Languages the therapist can conduct sessions in'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='profile_completion_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='treatment_approaches',
            field=models.JSONField(blank=True, default=dict, help_text='Therapy methods and approaches used', null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='video_session_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='patient_profile_pics/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='license_number',
            field=models.CharField(blank=True, help_text='License number format: AA-123456', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='therapist_profile_pics/'),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_profile_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='years_of_experience',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
