# Generated by Django 4.2.14 on 2025-02-25 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userpreferences_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name_plural': 'User settings'},
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='crisis_mode',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='display_preferences',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='journaling_mode',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='passcode_protection',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notifications',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='privacy_level',
            field=models.CharField(default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(default='light', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
