# Generated by Django 4.2.14 on 2025-03-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_patientprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('therapist', 'Therapist')], help_text='Designates whether this user is a patient or therapist', max_length=10, null=True),
        ),
    ]
