# Generated by Django 4.2.14 on 2025-02-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='privacy_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Optional privacy configuration', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='therapy_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Optional therapy preferences', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wearable_data',
            field=models.JSONField(blank=True, default=dict, help_text='Optional wearable device data', null=True),
        ),
    ]
