# Generated by Django 4.2.14 on 2025-03-13 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'verbose_name': 'Patient Profile', 'verbose_name_plural': 'Patient Profiles'},
        ),
        migrations.AlterModelOptions(
            name='therapistprofile',
            options={'verbose_name': 'Therapist Profile', 'verbose_name_plural': 'Therapist Profiles'},
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='theme',
            new_name='theme_preferences',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='last_appointment',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='next_appointment',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='is_profile_complete',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='profile_completion_percentage',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='accessibility_settings',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='notification_settings',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='notifications',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='privacy_level',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='profile_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('therapist', 'Therapist')], default='patient', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='profile_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('therapist', 'Therapist')], default='patient', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersettings',
            name='privacy_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('therapist', 'Therapist'), ('admin', 'Admin')], default='patient', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_type',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='pain_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='available_days',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='languages_spoken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='treatment_approaches',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
