version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS=*
      - DJANGO_ENV=development
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
