# Generated by Django 4.2.7 on 2025-05-22 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("AI_engine", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="useranalysis",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="therapyrecommendation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="socialinteractionanalysis",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="medicationeffectanalysis",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="conversationsummary",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="communicationpatternanalysis",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="aiinsight",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="useranalysis",
            index=models.Index(
                fields=["user", "-analysis_date"], name="AI_engine_u_user_id_024de3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useranalysis",
            index=models.Index(
                fields=["mood_score"], name="AI_engine_u_mood_sc_066eec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="therapyrecommendation",
            index=models.Index(
                fields=["user", "-created_at"], name="AI_engine_t_user_id_c48195_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="therapyrecommendation",
            index=models.Index(
                fields=["recommendation_type"], name="AI_engine_t_recomme_e1f9f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socialinteractionanalysis",
            index=models.Index(
                fields=["user", "-analysis_date"], name="AI_engine_s_user_id_614b8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socialinteractionanalysis",
            index=models.Index(
                fields=["engagement_score"], name="AI_engine_s_engagem_983306_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicationeffectanalysis",
            index=models.Index(
                fields=["user", "-analysis_date"], name="AI_engine_m_user_id_69d917_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationsummary",
            index=models.Index(
                fields=["conversation_id"], name="AI_engine_c_convers_c364d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationsummary",
            index=models.Index(
                fields=["user", "conversation_id"],
                name="AI_engine_c_user_id_e0dfc3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="communicationpatternanalysis",
            index=models.Index(
                fields=["user", "-analysis_date"], name="AI_engine_c_user_id_374966_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiinsight",
            index=models.Index(
                fields=["user", "-created_at"], name="AI_engine_a_user_id_4a66f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiinsight",
            index=models.Index(
                fields=["insight_type", "priority"],
                name="AI_engine_a_insight_7d7e84_idx",
            ),
        ),
    ]
