# Generated by Django 4.2.7 on 2025-05-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AI_engine", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialinteractionanalysis",
            name="growth_areas",
            field=models.JSONField(
                default=list, help_text="Areas for growth and improvement"
            ),
        ),
        migrations.AddField(
            model_name="socialinteractionanalysis",
            name="suggested_interventions",
            field=models.JSONField(default=list, help_text="Suggested interventions"),
        ),
    ]
