# Generated by Django 4.2.7 on 2025-05-27 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("AI_engine", "0003_socialinteractionanalysis_growth_areas_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrisisEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_content",
                    models.TextField(
                        help_text="Truncated content of the triggering message"
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="AI confidence score for crisis detection"
                    ),
                ),
                (
                    "crisis_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical Risk"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "matched_terms",
                    models.JSONField(
                        default=list, help_text="Terms that triggered crisis detection"
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                ("staff_notified", models.BooleanField(default=False)),
                ("follow_up_required", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crisis_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Crisis Event",
                "verbose_name_plural": "Crisis Events",
                "ordering": ["-timestamp"],
            },
        ),
    ]
