# Generated by Django 4.2.7 on 2025-05-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AI_engine", "0004_crisisevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="communicationpatternanalysis",
            name="ai_insights",
            field=models.JSONField(
                default=dict,
                help_text="AI-generated insights about communication patterns",
            ),
        ),
        migrations.AddField(
            model_name="communicationpatternanalysis",
            name="engagement_score",
            field=models.FloatField(default=0.0, help_text="Overall engagement score"),
        ),
        migrations.AddIndex(
            model_name="communicationpatternanalysis",
            index=models.Index(
                fields=["engagement_score"], name="AI_engine_c_engagem_205955_idx"
            ),
        ),
    ]
