# Generated by Django 4.2.7 on 2025-05-22 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chatbot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatbotconversation",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users participating in the conversation",
                related_name="participated_chatbot_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatbotconversation",
            name="user",
            field=models.ForeignKey(
                help_text="The user who owns this conversation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_chatbot_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["conversation", "timestamp"],
                name="chatbot_cha_convers_a85429_idx",
            ),
        ),
    ]
