# Generated by Django 4.2.7 on 2025-05-27 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chatbot", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversationsummary",
            name="conversation",
        ),
        migrations.AddField(
            model_name="conversationsummary",
            name="conversation_id",
            field=models.CharField(
                default=1, help_text="ID of the conversation", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conversationsummary",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation_summaries",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chatbotconversation",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this conversation is active"
            ),
        ),
        migrations.AlterField(
            model_name="chatbotconversation",
            name="title",
            field=models.CharField(
                blank=True, help_text="Title of the conversation", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="conversationsummary",
            name="id",
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name="chatbotconversation",
            index=models.Index(
                fields=["user", "-last_activity"], name="chatbot_cha_user_id_4c5469_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotconversation",
            index=models.Index(
                fields=["is_active", "-last_activity"],
                name="chatbot_cha_is_acti_f07d22_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotconversation",
            index=models.Index(
                fields=["-created_at"], name="chatbot_cha_created_1520d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["is_bot", "timestamp"], name="chatbot_cha_is_bot_ec59f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["-timestamp"], name="chatbot_cha_timesta_c63751_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationsummary",
            index=models.Index(
                fields=["conversation_id", "-created_at"],
                name="chatbot_con_convers_f8655e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationsummary",
            index=models.Index(
                fields=["user", "-created_at"], name="chatbot_con_user_id_dcfeb5_idx"
            ),
        ),
    ]
