# Generated by Django 4.2.14 on 2025-04-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_handler", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediafile",
            name="object_id",
        ),
        migrations.AddField(
            model_name="mediafile",
            name="object_id",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                db_index=True,
                help_text="ID of the related object",
            ),
        ),
    ]
