# Generated by Django 4.2.14 on 2025-03-13 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("media_handler", "0002_mediafile_uploaded_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
