# Generated by Django 4.2.14 on 2025-04-27 09:12

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("journal", "0002_journalcategory_alter_journalentry_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoodCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("color_code", models.CharField(default="#7FB3D5", max_length=20)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name_plural": "Mood Categories",
            },
        ),
        migrations.CreateModel(
            name="MoodTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_triggers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "user")},
            },
        ),
        migrations.CreateModel(
            name="MoodLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mood_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "energy_level",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Very Low"),
                            (2, "Low"),
                            (3, "Moderate"),
                            (4, "High"),
                            (5, "Very High"),
                        ],
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "activities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        help_text="Activities that may have influenced mood",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "symptoms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        help_text="Physical or emotional symptoms experienced",
                        null=True,
                        size=None,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("weather", models.CharField(blank=True, max_length=100, null=True)),
                ("logged_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mood_logs",
                        to="mood.moodcategory",
                    ),
                ),
                (
                    "journal_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mood_log",
                        to="journal.journalentry",
                    ),
                ),
                (
                    "triggers",
                    models.ManyToManyField(
                        blank=True, related_name="mood_logs", to="mood.moodtrigger"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mood_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-logged_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "logged_at"],
                        name="mood_moodlo_user_id_1afc91_idx",
                    )
                ],
            },
        ),
    ]
