# Generated by Django 4.2.14 on 2025-04-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mood", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moodlog",
            name="location",
        ),
        migrations.RemoveField(
            model_name="moodlog",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="moodlog",
            name="symptoms",
        ),
        migrations.RemoveField(
            model_name="moodlog",
            name="triggers",
        ),
        migrations.RemoveField(
            model_name="moodlog",
            name="weather",
        ),
        migrations.AlterField(
            model_name="moodlog",
            name="activities",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Exercise", "Exercise"),
                    ("Meditation", "Meditation"),
                    ("Reading", "Reading"),
                    ("Socializing", "Socializing"),
                    ("Cooking", "Cooking"),
                    ("Working", "Working"),
                    ("Sleeping", "Sleeping"),
                    ("Walking", "Walking"),
                    ("Running", "Running"),
                    ("Yoga", "Yoga"),
                    ("Dancing", "Dancing"),
                    ("Gaming", "Gaming"),
                    ("Traveling", "Traveling"),
                    ("Shopping", "Shopping"),
                    ("Listening to Music", "Listening to Music"),
                    ("Watching TV", "Watching TV"),
                    ("Gardening", "Gardening"),
                    ("Art", "Art"),
                    ("Writing", "Writing"),
                    ("Cleaning", "Cleaning"),
                ],
                help_text="Select one activity from a fixed list",
                max_length=50,
                null=True,
            ),
        ),
    ]
