# Generated by Django 4.2.14 on 2025-04-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mood", "0002_remove_moodlog_location_remove_moodlog_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moodlog",
            name="category",
        ),
        migrations.DeleteModel(
            name="MoodCategory",
        ),
    ]
