# Generated by Django 4.2.14 on 2025-04-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mood", "0003_remove_moodlog_category_delete_moodcategory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MoodTrigger",
        ),
    ]
