# Generated by Django 4.2.7 on 2025-05-22 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SessionNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField()),
                (
                    "session_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the therapy session occurred",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-session_date", "-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TherapistProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("specializations", models.JSONField(default=list)),
                (
                    "education",
                    models.JSONField(
                        default=list, help_text="List of educational qualifications"
                    ),
                ),
                ("experience", models.JSONField(default=list)),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("license_number", models.CharField(max_length=100, unique=True)),
                ("license_expiry", models.DateField(blank=True, null=True)),
                (
                    "available_days",
                    models.JSONField(
                        default=dict,
                        help_text="Dictionary of available days and time slots",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("profile_completion", models.FloatField(default=0)),
                (
                    "video_session_link",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verification_notes", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_documents", models.JSONField(default=list)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="therapist_profile_pics/"
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("total_ratings", models.PositiveIntegerField(default=0)),
                ("total_sessions", models.PositiveIntegerField(default=0)),
                (
                    "languages",
                    models.JSONField(
                        default=list,
                        help_text="List of languages spoken by the therapist",
                    ),
                ),
                (
                    "therapy_types",
                    models.JSONField(
                        default=list, help_text="Types of therapy offered"
                    ),
                ),
                ("accepts_insurance", models.BooleanField(default=False)),
                (
                    "insurance_providers",
                    models.JSONField(
                        default=list, help_text="List of accepted insurance providers"
                    ),
                ),
                (
                    "session_duration",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Default session duration in minutes",
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
            },
        ),
    ]
