# Generated by Django 4.2.7 on 2025-05-22 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("therapist", "0001_initial"),
        ("appointments", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapistprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="therapist_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sessionnote",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_note",
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="sessionnote",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "patient"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_session_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sessionnote",
            name="therapist",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "therapist"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="therapist_session_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="therapistprofile",
            index=models.Index(fields=["user"], name="therapist_t_user_id_6b9d21_idx"),
        ),
        migrations.AddIndex(
            model_name="therapistprofile",
            index=models.Index(
                fields=["is_verified", "verification_status"],
                name="therapist_t_is_veri_be77c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionnote",
            index=models.Index(
                fields=["-session_date"], name="therapist_s_session_22a96f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionnote",
            index=models.Index(
                fields=["therapist", "patient"], name="therapist_s_therapi_cac6e9_idx"
            ),
        ),
    ]
