# Generated by Django 4.2.14 on 2025-03-11 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("therapist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapistprofile",
            name="available_days",
            field=models.JSONField(
                default=list, help_text="Weekly availability schedule"
            ),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="consultation_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="languages_spoken",
            field=models.JSONField(
                default=list,
                help_text="Languages the therapist can conduct sessions in",
            ),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="license_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="treatment_approaches",
            field=models.JSONField(
                default=list, help_text="List of therapy methods and approaches used"
            ),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="video_session_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="therapistprofile",
            name="license_number",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="License number must be in format: AA-123456",
                        regex="^[A-Z]{2}-\\d{6}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="therapistprofile",
            name="years_of_experience",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
