# Generated by Django 4.2.7 on 2025-05-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("therapist", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapistprofile",
            name="license_number",
            field=models.CharField(
                blank=True,
                help_text="Professional license number (can be added later)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="therapistprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("license_number__isnull", False),
                    models.Q(("license_number__exact", ""), _negated=True),
                ),
                fields=("license_number",),
                name="unique_license_number_when_not_null",
            ),
        ),
    ]
