# Generated by Django 4.2.14 on 2025-04-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("therapist", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
