# Generated by Django 4.2.7 on 2025-05-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("therapist", "0003_alter_therapistprofile_license_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapistprofile",
            name="license_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Professional license number (can be added later)",
                max_length=50,
                null=True,
            ),
        ),
    ]
