# Generated by Django 4.2.14 on 2025-04-15 20:52

from django.db import migrations
from django.db.migrations.operations.base import Operation

class NoOpRemoveField(Operation):
    """
    A migration operation that removes the 'unique_id' field from the state
    if it exists. (No-op at the database level.)
    """
    reversible = True

    def state_forwards(self, app_label, state):
        model_key = (app_label, 'therapistprofile')
        if model_key in state.models:
            fields = state.models[model_key].fields
            # Remove unique_id if it exists, otherwise do nothing.
            if "unique_id" in fields:
                del fields["unique_id"]

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        pass

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        pass

    def describe(self):
        return "No-op removal of unique_id field if it exists."

class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0003_alter_appointment_status'),
    ]

    operations = [
        NoOpRemoveField(),
    ]
