# Generated by Django 4.2.14 on 2025-03-12 22:35

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("therapist", "0003_sessionnote_clientfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapistprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="is_profile_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="profile_completion_percentage",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="therapistprofile",
            name="available_days",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Weekly availability schedule",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="therapistprofile",
            name="languages_spoken",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Languages the therapist can conduct sessions in",
            ),
        ),
        migrations.AlterField(
            model_name="therapistprofile",
            name="license_number",
            field=models.CharField(
                blank=True,
                help_text="License number format: AA-123456",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="therapistprofile",
            name="specialization",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="therapistprofile",
            name="treatment_approaches",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Therapy methods and approaches used",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="therapistprofile",
            name="years_of_experience",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
