# Generated by Django 4.2.14 on 2025-03-12 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('therapist', '0004_therapistprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_profile_therapist', to=settings.AUTH_USER_MODEL),
        ),
    ]
