# Generated by Django 4.2.7 on 2025-05-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("therapist", "0002_fix_experience_field"),
        ("therapist", "0004_alter_therapistprofile_license_number"),
    ]

    operations = []
