# Generated by Django 4.2.14 on 2025-04-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0004_remove_therapistprofile_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistprofile',
            name='treatment_approaches',
            field=models.JSONField(blank=True, default=list, help_text='List of therapy methods and approaches used'),
        ),
    ]
