# Generated by Django 4.2.7 on 2025-05-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("therapist", "0005_merge_20250527_1332"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapistprofile",
            name="experience",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
