# Generated by Django 4.2.14 on 2025-03-13 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("therapist", "0006_therapistprofile_profile_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapistprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="therapist_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
