# Generated by Django 4.2.14 on 2025-03-13 23:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("therapist", "0007_alter_therapistprofile_user"),
    ]

    operations = []
