# Generated by Django 4.2.14 on 2025-03-13 23:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("therapist", "0008_populate_session_dates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientfeedback",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="sessionnote",
            options={"ordering": ["-session_date", "-timestamp"]},
        ),
        migrations.AddField(
            model_name="clientfeedback",
            name="session_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the therapy session occurred",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sessionnote",
            name="session_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the therapy session occurred",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sessionnote",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="last_verification_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="verification_documents",
            field=models.FileField(
                blank=True, null=True, upload_to="verification_docs/"
            ),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="verification_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="clientfeedback",
            name="feedback",
            field=models.TextField(
                help_text="Provide detailed feedback about your session"
            ),
        ),
        migrations.AlterField(
            model_name="clientfeedback",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "patient"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_feedback_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="clientfeedback",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "1 - Poor"),
                    (2, "2 - Fair"),
                    (3, "3 - Good"),
                    (4, "4 - Very Good"),
                    (5, "5 - Excellent"),
                ],
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="clientfeedback",
            name="therapist",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "therapist"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="therapist_feedback_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sessionnote",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "patient"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_session_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sessionnote",
            name="therapist",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "therapist"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="therapist_session_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="clientfeedback",
            index=models.Index(
                fields=["-timestamp"], name="therapist_c_timesta_20cee1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientfeedback",
            index=models.Index(
                fields=["therapist", "rating"], name="therapist_c_therapi_ba58ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionnote",
            index=models.Index(
                fields=["-session_date"], name="therapist_s_session_22a96f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionnote",
            index=models.Index(
                fields=["therapist", "patient"], name="therapist_s_therapi_cac6e9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="clientfeedback",
            constraint=models.UniqueConstraint(
                fields=("patient", "therapist", "session_date"),
                name="unique_session_feedback",
            ),
        ),
    ]
