# Generated by Django 4.2.14 on 2025-03-14 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("therapist", "0011_availableday_alter_therapistprofile_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="appointment",
            name="appointment_future_date",
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "date_time__gt",
                        datetime.datetime(
                            2025, 3, 14, 20, 56, 3, 628332, tzinfo=datetime.timezone.utc
                        ),
                    )
                ),
                name="appointment_future_date",
            ),
        ),
    ]
