# Generated by Django 4.2.14 on 2025-03-15 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0015_remove_appointment_appointment_future_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='appointment_future_date',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('date_time__gt', datetime.datetime(2025, 3, 15, 1, 13, 14, 156876, tzinfo=datetime.timezone.utc))), name='appointment_future_date'),
        ),
    ]
