# Generated by Django 4.2.14 on 2025-04-27 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("feeds", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="is_archived",
        ),
        migrations.RemoveField(
            model_name="post",
            name="is_edited",
        ),
        migrations.RemoveField(
            model_name="post",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="post",
            name="is_pinned",
        ),
        migrations.RemoveField(
            model_name="post",
            name="link_description",
        ),
        migrations.RemoveField(
            model_name="post",
            name="link_image",
        ),
        migrations.RemoveField(
            model_name="post",
            name="link_title",
        ),
        migrations.RemoveField(
            model_name="post",
            name="topics",
        ),
        migrations.AlterField(
            model_name="post",
            name="visibility",
            field=models.CharField(default="public", editable=False, max_length=20),
        ),
        migrations.CreateModel(
            name="FeedPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("object_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="topics",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mental_health", "Mental Health"),
                    ("therapy", "Therapy"),
                    ("self_care", "Self Care"),
                    ("mindfulness", "Mindfulness"),
                    ("stress_management", "Stress Management"),
                    ("relationships", "Relationships"),
                    ("personal_growth", "Personal Growth"),
                    ("anxiety", "Anxiety"),
                    ("depression", "Depression"),
                    ("wellness", "Wellness"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
