# Generated by Django 4.2.14 on 2025-04-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0003_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.CharField(
                choices=[
                    ("mental_health", "Mental Health"),
                    ("therapy", "Therapy"),
                    ("self_care", "Self Care"),
                    ("mindfulness", "Mindfulness"),
                    ("stress_management", "Stress Management"),
                    ("relationships", "Relationships"),
                    ("personal_growth", "Personal Growth"),
                    ("anxiety", "Anxiety"),
                    ("depression", "Depression"),
                    ("wellness", "Wellness"),
                    ("motivation", "Motivation"),
                    ("resilience", "Resilience"),
                    ("empathy", "Empathy"),
                    ("gratitude", "Gratitude"),
                    ("happiness", "Happiness"),
                    ("positivity", "Positivity"),
                    ("relaxation", "Relaxation"),
                    ("coping_skills", "Coping Skills"),
                    ("emotional_intelligence", "Emotional Intelligence"),
                    ("mental_resilience", "Mental Resilience"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
