# Generated by Django 4.2.14 on 2025-04-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0004_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[("text", "Text"), ("image", "Image"), ("video", "Video")],
                default="text",
                max_length=20,
            ),
        ),
    ]
