# Generated by Django 4.2.14 on 2025-04-27 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("feeds", "0005_alter_post_post_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="content_type",
            field=models.ForeignKey(
                help_text="Type of content being reacted to (Post, Comment, etc.)",
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="object_id",
            field=models.PositiveIntegerField(
                help_text="ID of the content being reacted to"
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="reaction_type",
            field=models.CharField(
                choices=[
                    ("like", "Like 👍"),
                    ("love", "Love ❤️"),
                    ("support", "Support 🤝"),
                    ("insightful", "Insightful 💡"),
                    ("celebrate", "Celebrate 🎉"),
                ],
                help_text="Type of reaction",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="user",
            field=models.ForeignKey(
                help_text="User who created the reaction",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
