# Generated by Django 4.2.14 on 2025-04-27 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("feeds", "0006_alter_reaction_content_type_alter_reaction_object_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="hiddenpost",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="hiddenpost",
            name="post",
        ),
        migrations.RemoveField(
            model_name="hiddenpost",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="savedpost",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="savedpost",
            name="post",
        ),
        migrations.RemoveField(
            model_name="savedpost",
            name="user",
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.CharField(
                choices=[
                    ("mental_health", "Mental Health"),
                    ("therapy", "Therapy"),
                    ("self_care", "Self Care"),
                    ("mindfulness", "Mindfulness"),
                    ("stress_management", "Stress Management"),
                    ("relationships", "Relationships"),
                    ("personal_growth", "Personal Growth"),
                    ("anxiety", "Anxiety"),
                    ("depression", "Depression"),
                    ("wellness", "Wellness"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="object_id",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="reaction_type",
            field=models.CharField(
                choices=[
                    ("like", "Like 👍"),
                    ("love", "Love ❤️"),
                    ("support", "Support 🤝"),
                    ("insightful", "Insightful 💡"),
                    ("celebrate", "Celebrate 🎉"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="FeedPost",
        ),
        migrations.DeleteModel(
            name="HiddenPost",
        ),
        migrations.DeleteModel(
            name="SavedPost",
        ),
    ]
