# Generated by Django 4.2.14 on 2025-03-04 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="conversation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="last_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_message_conversations",
                to="messaging.message",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[("text", "Text"), ("system", "System"), ("action", "Action")],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="read_by",
            field=models.ManyToManyField(
                blank=True, related_name="read_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "timestamp"],
                name="messaging_m_convers_91f1f5_idx",
            ),
        ),
    ]
