# Generated by Django 4.2.7 on 2025-05-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupmessage",
            options={"ordering": ["timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="onetoonemessage",
            options={"ordering": ["timestamp"]},
        ),
        migrations.RemoveIndex(
            model_name="groupmessage",
            name="messaging_g_timesta_f59cdd_idx",
        ),
        migrations.RemoveIndex(
            model_name="groupmessage",
            name="messaging_g_sender__a38088_idx",
        ),
        migrations.RemoveIndex(
            model_name="groupmessage",
            name="messaging_g_message_a1fccb_idx",
        ),
        migrations.RemoveIndex(
            model_name="onetoonemessage",
            name="messaging_o_timesta_c24e61_idx",
        ),
        migrations.RemoveIndex(
            model_name="onetoonemessage",
            name="messaging_o_sender__19dce8_idx",
        ),
        migrations.RemoveIndex(
            model_name="onetoonemessage",
            name="messaging_o_message_3fd987_idx",
        ),
        migrations.AddIndex(
            model_name="groupmessage",
            index=models.Index(
                fields=["timestamp"], name="messaging_g_timesta_7a9ded_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmessage",
            index=models.Index(
                fields=["sender", "timestamp"], name="messaging_g_sender__1a16ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmessage",
            index=models.Index(
                fields=["message_type", "timestamp"],
                name="messaging_g_message_b82e26_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="onetoonemessage",
            index=models.Index(
                fields=["timestamp"], name="messaging_o_timesta_1e31f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onetoonemessage",
            index=models.Index(
                fields=["sender", "timestamp"], name="messaging_o_sender__6add11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onetoonemessage",
            index=models.Index(
                fields=["message_type", "timestamp"],
                name="messaging_o_message_f6ea31_idx",
            ),
        ),
    ]
