# Generated by Django 4.2.14 on 2025-04-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_onetoonemessage_edit_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotmessage',
            name='edit_history',
            field=models.JSONField(default=list, help_text='List of previous message versions'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='edit_history',
            field=models.JSONField(default=list, help_text='List of previous message versions'),
        ),
    ]
