# Generated by Django 4.2.14 on 2025-03-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "messaging",
            "0006_chatbotconversation_chatbotmessage_groupconversation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotmessage",
            name="is_typing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatbotmessage",
            name="reactions",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="is_typing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="reactions",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="onetoonemessage",
            name="is_typing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="onetoonemessage",
            name="reactions",
            field=models.JSONField(default=dict),
        ),
    ]
