# Generated by Django 4.2.14 on 2025-03-14 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "messaging",
            "0007_chatbotmessage_is_typing_chatbotmessage_reactions_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotmessage",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatbotmessage",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatbotmessage",
            name="deletion_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatbotmessage",
            name="edit_history",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="chatbotmessage",
            name="edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatbotmessage",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatbotmessage",
            name="edited_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_edited_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatbotmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Message"),
                    ("image", "Image Message"),
                    ("file", "File Attachment"),
                    ("system", "System Message"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chatbotmessage",
            name="metadata",
            field=models.JSONField(
                default=dict, help_text="Store additional message metadata"
            ),
        ),
        migrations.AddField(
            model_name="groupconversation",
            name="archive_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupconversation",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="groupconversation",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="deletion_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="edit_history",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="edited_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_edited_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="metadata",
            field=models.JSONField(
                default=dict, help_text="Store additional message metadata"
            ),
        ),
        migrations.AddField(
            model_name="onetooneconversation",
            name="archive_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="onetooneconversation",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="onetooneconversation",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="onetoonemessage",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="onetoonemessage",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="onetoonemessage",
            name="deletion_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="onetoonemessage",
            name="edit_history",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="onetoonemessage",
            name="edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="onetoonemessage",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="onetoonemessage",
            name="edited_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_edited_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="onetoonemessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Message"),
                    ("image", "Image Message"),
                    ("file", "File Attachment"),
                    ("system", "System Message"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="onetoonemessage",
            name="metadata",
            field=models.JSONField(
                default=dict, help_text="Store additional message metadata"
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotmessage",
            index=models.Index(
                fields=["-timestamp"], name="messaging_c_timesta_0ce6f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotmessage",
            index=models.Index(
                fields=["sender", "-timestamp"], name="messaging_c_sender__f83db8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotmessage",
            index=models.Index(
                fields=["message_type", "-timestamp"],
                name="messaging_c_message_a4770f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="groupmessage",
            index=models.Index(
                fields=["-timestamp"], name="messaging_g_timesta_f59cdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmessage",
            index=models.Index(
                fields=["sender", "-timestamp"], name="messaging_g_sender__a38088_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmessage",
            index=models.Index(
                fields=["message_type", "-timestamp"],
                name="messaging_g_message_a1fccb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="onetoonemessage",
            index=models.Index(
                fields=["-timestamp"], name="messaging_o_timesta_c24e61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onetoonemessage",
            index=models.Index(
                fields=["sender", "-timestamp"], name="messaging_o_sender__19dce8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onetoonemessage",
            index=models.Index(
                fields=["message_type", "-timestamp"],
                name="messaging_o_message_3fd987_idx",
            ),
        ),
    ]
