# Generated by Django 4.2.14 on 2025-03-14 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("messaging", "0008_chatbotmessage_deleted_chatbotmessage_deleted_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatbotmessage",
            name="is_typing",
        ),
        migrations.RemoveField(
            model_name="groupmessage",
            name="is_typing",
        ),
        migrations.RemoveField(
            model_name="onetoonemessage",
            name="is_typing",
        ),
        migrations.CreateModel(
            name="MessageEditHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "previous_content",
                    models.TextField(help_text="The content before this edit"),
                ),
                ("edited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Edit History",
                "verbose_name_plural": "Message Edit Histories",
                "ordering": ["-edited_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="messaging_m_content_caeab6_idx",
                    ),
                    models.Index(
                        fields=["edited_at"], name="messaging_m_edited__c25c60_idx"
                    ),
                ],
            },
        ),
    ]
