# Generated by Django 4.2.14 on 2025-03-15 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0009_remove_chatbotmessage_is_typing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onetooneconversation',
            options={'verbose_name': 'One-to-One Conversation', 'verbose_name_plural': 'One-to-One Conversations'},
        ),
        migrations.AddField(
            model_name='chatbotconversation',
            name='archive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotconversation',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatbotconversation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatbotconversation',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chatbotconversation',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupconversation',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OneToOneConversationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.onetooneconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_onetooneconversation_participants',
                'unique_together': {('conversation', 'user')},
            },
        ),
        migrations.AlterField(
            model_name='onetooneconversation',
            name='participants',
            field=models.ManyToManyField(related_name='onetoone_conversations', through='messaging.OneToOneConversationParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
