# Generated by Django 4.2.14 on 2025-03-11 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="blood_type",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="emergency_contact",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="last_appointment",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="next_appointment",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="pain_level",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="treatment_plan",
            field=models.TextField(blank=True, null=True),
        ),
    ]
