# Generated by Django 4.2.14 on 2025-04-15 20:52

from django.db import migrations
from django.db.migrations.operations.base import Operation


class NoOpRemoveField(Operation):
    """
    A migration operation that removes a specified field from the state if it exists. No-op at the database level.
    """
    reversible = True

    def __init__(self, model_name, name):
        self.model_name = model_name
        self.name = name

    def state_forwards(self, app_label, state):
        model_key = (app_label, self.model_name)
        if model_key in state.models:
            fields = state.models[model_key].fields
            if self.name in fields:
                del fields[self.name]

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        pass

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        pass

    def describe(self):
        return f"No-op removal of {self.name} field if it exists."


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_delete_moodlog'),
    ]

    operations = [
        NoOpRemoveField('patientprofile', 'unique_id'),
    ]
