# Generated by Django 4.2.14 on 2025-03-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0004_add_timestamp_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patientprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Patient Profiles",
            },
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A Positive"),
                    ("A-", "A Negative"),
                    ("B+", "B Positive"),
                    ("B-", "B Negative"),
                    ("AB+", "AB Positive"),
                    ("AB-", "AB Negative"),
                    ("O+", "O Positive"),
                    ("O-", "O Negative"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="emergency_contact",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Must include name, relationship, and phone",
            ),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="patient_profile_pics/%Y/%m/"
            ),
        ),
    ]
