# Generated by Django 4.2.14 on 2025-03-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0005_alter_patientprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="emergency_contact",
            field=models.JSONField(
                help_text="Must include name, relationship, and phone"
            ),
        ),
    ]
