# Generated by Django 4.2.14 on 2025-03-12 22:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0007_alter_patientprofile_emergency_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientprofile",
            name="emergency_contact",
        ),
    ]
