# Generated by Django 4.2.14 on 2025-03-13 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patient", "0010_patientprofile_profile_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
