# Generated by Django 4.2.14 on 2025-03-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_alter_patientprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('therapist', 'Therapist')], default='patient', max_length=10),
        ),
    ]
