# Generated by Django 4.2.7 on 2025-05-22 17:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_id",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                ("appointment_date", models.DateTimeField()),
                (
                    "duration",
                    models.DurationField(default=datetime.timedelta(seconds=3600)),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("rescheduled", "Rescheduled"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("missed", "Missed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("video_session_link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("original_date", models.DateTimeField(blank=True, null=True)),
                ("reschedule_count", models.PositiveIntegerField(default=0)),
                ("last_rescheduled", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_recommendations",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="AI-generated recommendations for the therapy session",
                    ),
                ),
                (
                    "pain_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Patient's pain level (0-10) reported during appointment",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["-appointment_date"],
            },
        ),
        migrations.CreateModel(
            name="WaitingListEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_date", models.DateField()),
                (
                    "preferred_time_slots",
                    models.JSONField(
                        help_text="List of preferred time slots in HH:MM format"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("notified", "Notified"),
                            ("booked", "Booked"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["requested_date", "created_at"],
            },
        ),
    ]
