# Generated by Django 4.2.7 on 2025-05-22 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitinglistentry",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waiting_list_entries",
                to="patient.patientprofile",
            ),
        ),
    ]
