# Generated by Django 4.2.7 on 2025-05-22 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("appointments", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("therapist", "0001_initial"),
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="patient.patientprofile",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="rescheduled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rescheduled_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="therapist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="therapist.therapistprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="waitinglistentry",
            index=models.Index(
                fields=["requested_date"], name="appointment_request_3b0228_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waitinglistentry",
            index=models.Index(fields=["status"], name="appointment_status_e61455_idx"),
        ),
        migrations.AddIndex(
            model_name="waitinglistentry",
            index=models.Index(
                fields=["therapist", "status"], name="appointment_therapi_3ab338_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_date"], name="appointment_appoint_5be6a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status"], name="appointment_status_8fe9d7_idx"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "status"], name="appointment_patient_44acdc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["therapist", "status"], name="appointment_therapi_e09ec9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["therapist", "appointment_date"],
                name="appointment_therapi_3555d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "appointment_date"],
                name="appointment_patient_8037cd_idx",
            ),
        ),
    ]
