# Generated by Django 5.1.7 on 2025-03-17 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("in_app_notifications", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="NotificationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "template_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="notification",
            name="expiry_after_creation",
        ),
        migrations.RemoveConstraint(
            model_name="notification",
            name="unique_notification_per_user",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_user_id_427e4b_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_created_46ad24_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="expiry_index",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="priority_index",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="url",
            new_name="link",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_notific_d6e074_idx",
            old_name="notificatio_notific_f2898f_idx",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="object_id",
        ),
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(default="general", max_length=50),
        ),
        migrations.AddField(
            model_name="notification",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(default="Untitled", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="websocket_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="priority",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="disabled_notification_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="disabled_preferences",
                to="notifications.notificationtype",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="notifications.notificationtype",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "created_at"],
                name="notificatio_user_id_8a7c6b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["category"], name="notificatio_categor_fd561f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["priority"], name="notificatio_priorit_bf8ea0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "category", "is_read"],
                name="notificatio_user_id_5fc26e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type", "created_at"],
                name="notificatio_notific_5e6e57_idx",
            ),
        ),
    ]
