# Generated by Django 5.1.7 on 2025-03-17 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("notifications", "0003_notificationpreference_notificationtype_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationtype",
            old_name="is_active",
            new_name="default_enabled",
        ),
        migrations.RemoveField(
            model_name="notificationtype",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="notificationtype",
            name="template_name",
        ),
        migrations.AddField(
            model_name="notificationtype",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="User groups that can receive this notification type",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="notificationtype",
            name="is_global",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="disabled_notification_types",
            field=models.ManyToManyField(
                blank=True, to="notifications.notificationtype"
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="notificationtype",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
